### ISSUE TITLE
waether: ssl certificate verify failed is not handled

### ISSUE THREAD

**Issue by andr2000** [andr2000/ufh-controller#1]
Traceback (most recent call last):
  File "./main.py", line 68, in <module>
    main()
  File "./main.py", line 49, in main
    weather.process()
  File "/mnt/data/projects/ufh-controller/weather.py", line 101, in process
    temperature = get_sinoptik()
  File "/mnt/data/projects/ufh-controller/weather.py", line 24, in get_sinoptik
    headers={'User-Agent' : ''})
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)

**Comment by andr2000** [comment]
Fixed by d8b70799b0c5ca8591e23398a379b19d6fdeb922
